### ISSUE TITLE
`count_histogram` tests on my system produce memory corruption warnings.

### ISSUE THREAD

**Issue by cristianberneanu** [diffix/pg_diffix#421]
```
----------------------------------------------------------------
-- Anonymizing count_histogram
----------------------------------------------------------------
SET ROLE diffix_test;
SET pg_diffix.session_access_level = 'anonymized_trusted';
SELECT diffix.count_histogram(id) FROM count_histogram_test;
WARNING:  problem in alloc set ExecutorState: detected write past chunk end in block 0x7fffc7ddd8a0, chunk 0x7fffc7ddf700
WARNING:  problem in alloc set ExecutorState: detected write past chunk end in block 0x7fffc7ddd8a0, chunk 0x7fffc7ddf700
    count_histogram
------------------------
 {{NULL,3},{1,4},{2,3}}
(1 row)

SELECT diffix.count_histogram(id, 5) FROM count_histogram_test;
 count_histogram
-----------------
 {{0,7},{5,2}}
(1 row)

----------------------------------------------------------------
-- Misc
----------------------------------------------------------------
SELECT diffix.unnest_histogram(x.histogram)
FROM (
  SELECT diffix.count_histogram(id) AS histogram
  FROM count_histogram_test
) x;
WARNING:  problem in alloc set ExecutorState: detected write past chunk end in block 0x7fffc7e0b540, chunk 0x7fffc7e0bad8
WARNING:  problem in alloc set ExecutorState: detected write past chunk end in block 0x7fffc7e0b540, chunk 0x7fffc7e0bad8
 unnest_histogram
------------------
 {NULL,3}
 {1,4}
 {2,3}
(3 rows)
```

**Comment by edongashi** [comment]
The array initialization inputs are probably wrong. Any way to get a stack trace of that warning?

**Comment by cristianberneanu** [comment]
Here is the stack-trace:
```
#0  0x00007f067e6a27a4 in errstart ()
#1  0x00007f067e6ca410 in ?? ()
#2  0x00007f067e6ca7e8 in ?? ()
#3  0x00007f067e3b5fd1 in standard_ExecutorEnd ()
#4  0x00007f0671998f31 in pg_diffix_ExecutorEnd (queryDesc=0x7fffc7dba080) at src/hooks.c:214
#5  0x00007f067e35bdd1 in PortalCleanup ()
#6  0x00007f067e6d397d in PortalDrop ()
#7  0x00007f067e55e678 in ?? ()
#8  0x00007f067e5604d3 in PostgresMain ()
#9  0x00007f067e4ca926 in ?? ()
#10 0x00007f067e4cb818 in PostmasterMain ()
#11 0x00007f067e1a7326 in main ()
```
Doesn't seem very relevant, as the corruption happens way before it.

If you can't reproduce the problem, I can have a go at it.

**Comment by cristianberneanu** [comment]
OK, I will look into it and let you know if I get stuck.
